### ISSUE TITLE
Unable to resolve configuration with compilerPath "**/xxx-yyy-gcc.exe" when -W build option is used

### ISSUE THREAD

**Issue by MaDill** [br-automation-com/vscode-brautomationtools#27]
When open an C file it show red wavy lines below the includes and sometimes also somewhere else. In Automationstudio everything is fine and the project and also be compiled.

The hint say, that it can't find the "Source", but I also can compile the project in Visual Studio Source without any issues.

![image](https://user-images.githubusercontent.com/7298934/145178955-f81a79c3-b327-4d52-9fbc-7045aab4b084.png)

Version information : AutomationStudio 4.8.2.72, VSC 1.62.3, Extension 0.0.4, ST Extension 1.10.6, C/C++ Extension from Microsoft 1.7.1

In the Microsoft C/C++ Extension it show 2 uncatched errors:

![image](https://user-images.githubusercontent.com/7298934/145179858-d4435579-dc46-445f-b74e-0c5bf12c9309.png)

In the output it show also:

![image](https://user-images.githubusercontent.com/7298934/145179962-70f34cd8-8ffa-49d0-bca0-7ad5b702d12a.png)

The path and the file exists on my harddisk.

**Comment by Radeonmann** [comment]
Thanks for the report. I will take a closer look as soon as I find time.

The two unhandled exceptions can be normal in the current state of our extension, if you already have a C/C++ file open when you open the workspace. There seems to be some timing problem / our extension is too slow to hand over the include paths...
But the C/C++ extension recovers, as soon as I provide the information. So as soon as you see "B&R Tools is now active" pop-up, the C/C++ extension will start to resolve the includes.

In your case there seems to be the issue, that the C/C++ extension cannot access the gcc executables which are shown in your last screenshot. The system includes (<bur/plctypes.h>, <stdio.h>...) are directly queried from gcc by the C/C++ extension. And because the C/C++ extension cannot access gcc, the headers are unknown.

Can you please check following steps, I don't know if all of them are relevant, but it's better to have more info than less 😉 :
- Did you trust the Workspace?
- Is the file C:\BrAutomation\AS48\AS\gnuinst\V6.3.0\bin\i686-elf-gcc.exe existing?
- Open PowerShell and try following command
  `C:\BrAutomation\AS48\AS\gnuinst\V6.3.0\bin\i686-elf-gcc.exe -v /dev/null -o /dev/null`
  This will output some options which the compiler would execute. I don't know how exactly the C/C++ extension makes the query, but it will be something like this.
- Enable debug level logging in the B&R and in the C++ extension and upload both logs here or somewhere accessible
  - B&R Extension:
    ![image](https://user-images.githubusercontent.com/13839232/145222791-0173d906-5f91-4cb0-ab67-859b3b853a0b.png)
  - C/C++ Extension:
    ![image](https://user-images.githubusercontent.com/13839232/145222690-ad53686f-9f74-4106-8786-fe09cbd15df6.png)

**Comment by Radeonmann** [comment]
Today evening I also had this issue one time for another gcc version. After reloading the window it worked again.

I guess it might be some other process, Windows, or an anti virus program which blocks the file access for a short time.

Is it always like this for you? Or does it happen only some times / once?

**Comment by MaDill** [comment]
> * Did you trust the Workspace?

The path where the project file and folders are below the trusted workspace. I set the trusted workspace for my whole project folder and the project is in a subfolder.

> * Is the file C:\BrAutomation\AS48\AS\gnuinst\V6.3.0\bin\i686-elf-gcc.exe existing?

Yes. As I wrote, I can also built by project without an issue.

> * Open PowerShell and try following command
>   `C:\BrAutomation\AS48\AS\gnuinst\V6.3.0\bin\i686-elf-gcc.exe -v /dev/null -o /dev/null`

PS C:\_Projects\DojoMDL\esmoTemplateTest> C:\BrAutomation\AS48\AS\gnuinst\V6.3.0\bin\i686-elf-gcc.exe -v /dev/null -o /dev/null
i686-elf-gcc.exe: error: /dev/null: No such file or directory
Using built-in specs.
COLLECT_GCC=C:\BrAutomation\AS48\AS\gnuinst\V6.3.0\bin\i686-elf-gcc.exe
COLLECT_LTO_WRAPPER=c:/brautomation/as48/as/gnuinst/v6.3.0/bin/../libexec/gcc/i686-elf/6.3.0/lto-wrapper.exe
Target: i686-elf
Configured with: ../gcc-6.3.0/configure --prefix=/opt/V6.3.0 --target=i686-elf --with-pic --with-newlib --enable-fully-dynamic-string --enable-languages=c,c++ --disable-initfini-array --disable-nls --disable-shared --disable-multilib --disable-threads --disable-tls --disable-win32-registry --enable-sjlj-exceptions --enable-frame-pointer --disable-__cxa_atexit --disable-libgomp --disable-libquadmath --disable-libssp --disable-libada --disable-libitm --disable-libstdcxx-verbose --disable-libstdcxx-visibility --with-default-libstdcxx-abi=gcc4-compatible --without-headers : (reconfigured) ../gcc-6.3.0/configure --prefix=/opt/V6.3.0 --target=i686-elf --with-pic --with-newlib --enable-fully-dynamic-string --enable-languages=c,c++ --disable-initfini-array --disable-nls --disable-shared --disable-multilib --disable-threads --disable-tls --disable-win32-registry --enable-sjlj-exceptions --enable-frame-pointer --disable-__cxa_atexit --disable-libgomp --disable-libquadmath --disable-libssp --disable-libada --disable-libitm --disable-libstdcxx-verbose --disable-libstdcxx-visibility --with-default-libstdcxx-abi=gcc4-compatible --with-headers
Thread model: single
gcc version 6.3.0 (GCC)
PS C:\_Projects\DojoMDL\esmoTemplateTest> 

> * Enable debug level logging in the B&R and in the C++ extension and upload both logs here or somewhere accessible

The logging for the B&R extension was already "Debug". The logging for C++ is now set from "Error" to "Debug".

> Is it always like this for you? Or does it happen only some times / once?

Yes.

**Comment by Radeonmann** [comment]
You can find the log messages in the output window. You have to change the channel to `C/C++` and `vscode-brautomationtools` to see the C/C++ and our logs. After a configuration error, the C/C++ extension will have one more output channel `C/C++ configuration warnings`, which is what you sent me in the first message.
![image](https://user-images.githubusercontent.com/13839232/145367819-f5c12805-e9d7-4fdb-8fdf-8c99da7a5050.png)


It will be the easiest if you you just Ctrl + A / Ctrl + C the output window for each channel. VS Code would also log the files to disk somewhere in the %APPDATA% folder.

>> Is it always like this for you? Or does it happen only some times / once?

> Yes.

Yes to which one 😉? Always or only some times?

**Comment by MaDill** [comment]
Debug vscode-brautomationtools when opening a c file:

[10:58:39.993 - Debug] findAvailableASVersionsInUri(c:\BrAutomation) 
[10:58:40.038 -  Info] Start activation of B&R Automation Tools extension 
[10:58:40.097 -  Info] AS Version V4.8.0 found in c:\BrAutomation\AS48 
[10:58:40.820 -  Info] Activation of B&R Automation Tools extension finished 
[10:58:40.826 - Debug] CppConfigurationProvider.provideConfigurations() called for URI "file:///c:/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c" 
[10:58:40.826 - Debug] CppConfigurationProvider._getConfiguration() called for URI "file:///c:/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c" 
[10:58:41.157 - Debug] CppConfigurationProvider._getConfiguration() called for URI "file:///c:/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c" return: ({"uri":{"$mid":1,"fsPath":"c:\\_Projects\\DojoMDL\\XXXTemplateTest\\Logical\\Libraries\\XXX\\Messaging\\UM_Message\\UM_Message\\UM_Message.c","_sep":1,"path":"/C:/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c","scheme":"file"},"configuration":{"includePath":["c:\\_Projects\\DojoMDL\\XXXTemplateTest\\Temp\\Includes","c:\\_Projects\\DojoMDL\\XXXTemplateTest\\Logical\\Libraries\\BuR","c:\\_Projects\\DojoMDL\\XXXTemplateTest\\Logical\\Libraries\\XXX"],"defines":[],"compilerArgs":["-fPIC","-O0","-g","-Wall","-D","_DEFAULT_INCLUDES","-D","_SG4","-D","_BUR_FORMAT_BRELF","-W 5880 9233 9881"],"compilerPath":"c:\\BrAutomation\\AS48\\AS\\gnuinst\\V6.3.0\\bin\\i686-elf-gcc.exe"}})

C/C++

loggingLevel: Debug
Benutzerdefinierter Konfigurationsanbieter "B&R Automation Tools" registriert
cpptools/didChangeCppProperties
Es wurde der MSVC-IntelliSenseMode angegeben. Der Compiler (cl.exe) wird konfiguriert.
Der Compiler (cl.exe) kann nicht konfiguriert werden.
Es wurde kein geeigneter Compiler gefunden. Legen Sie "compilerPath" in "c_cpp_properties.json" fest.
Codesuchdienst initialisiert.
Es wurde der MSVC-IntelliSenseMode angegeben. Der Compiler (cl.exe) wird konfiguriert.
Der Compiler (cl.exe) kann nicht konfiguriert werden.
Es wurde kein geeigneter Compiler gefunden. Legen Sie "compilerPath" in "c_cpp_properties.json" fest.
  Ordner: C:/_PROJECTS/DOJOMDL/XXXTEMPLATETEST/ werden indiziert.
textDocument/didOpen: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c
Dateien werden ermittelt...
cpptools/didChangeCppProperties
cpptools/pauseParsing
cpptools/clearCustomConfigurations
Nach Syntaxfehlern wird gesucht: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c
cpptools/getCodeActions: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c (id: 2)
  Ordner wird verarbeitet (rekursiv): C:/_PROJECTS/DOJOMDL/XXXTEMPLATETEST/
cpptools/getFoldingRanges: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c (id: 3)
cpptools/getCodeActions: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c (id: 4)
cpptools/getSemanticTokens: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c (id: 5)
cpptools/getDocumentSymbols: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c (id: 6)
cpptools/getDocumentSymbols
cpptools/clearCustomConfigurations
cpptools/clearCustomConfigurations
cpptools/queryTranslationUnitSource: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c (id: 7)
Benutzerdefinierte Konfigurationen empfangen:
  uri: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c
  config: {
  "includePath": [
    "c:\\_Projects\\DojoMDL\\XXXTemplateTest\\Temp\\Includes",
    "c:\\_Projects\\DojoMDL\\XXXTemplateTest\\Logical\\Libraries\\BuR",
    "c:\\_Projects\\DojoMDL\\XXXTemplateTest\\Logical\\Libraries\\XXX"
  ],
  "defines": [],
  "compilerArgs": [
    "-fPIC",
    "-O0",
    "-g",
    "-Wall",
    "-D",
    "_DEFAULT_INCLUDES",
    "-D",
    "_SG4",
    "-D",
    "_BUR_FORMAT_BRELF",
    "-W 5880 9233 9881"
  ],
  "compilerPath": "c:\\BrAutomation\\AS48\\AS\\gnuinst\\V6.3.0\\bin\\i686-elf-gcc.exe"
}
cpptools/didChangeCustomConfiguration
Es wird versucht, Standardwerte vom C-Compiler in der Eigenschaft "compilerPath" abzurufen: c:\BrAutomation\AS48\AS\gnuinst\V6.3.0\bin\i686-elf-gcc.exe
Der Compiler für den Standard-C++-Sprachstandard wird über die Befehlszeile abgefragt: "c:\\BrAutomation\\AS48\\AS\\gnuinst\\V6.3.0\\bin\\i686-elf-gcc.exe" -x c++ -E -dM nul
Erkannte Sprachstandardversion: gnu++14
Der Compiler für den Standard-C-Sprachstandard wird über die Befehlszeile abgefragt: "c:\\BrAutomation\\AS48\\AS\\gnuinst\\V6.3.0\\bin\\i686-elf-gcc.exe" -x c -E -dM nul
Erkannte Sprachstandardversion: gnu11
Das Standardziel des Compilers wird über die Befehlszeile abgefragt: "c:\BrAutomation\AS48\AS\gnuinst\V6.3.0\bin\i686-elf-gcc.exe" -dumpmachine
Der Compiler hat den Standardzielwert zurückgegeben: i686-elf

Befehlszeile der Compilerabfrage: "c:\\BrAutomation\\AS48\\AS\\gnuinst\\V6.3.0\\bin\\i686-elf-gcc.exe" -fPIC -O0 -g -Wall -W 5880 9233 9881 -std=gnu11 -Wp,-v -E -dD -x c -m64  nul
Befehlszeile der Compilerabfrage: "c:\\brautomation\\as48\\as\\gnuinst\\v6.3.0\\bin\\i686-elf-gcc.exe" -fPIC -O0 -g -Wall -W 5880 9233 9881 -std=gnu11 -Wp,-v -E -dD -x c -m64  /dev/null
Fehler beim Abfragen des Compilers. Es wird ein Fallback auf den 32-Bit-intelliSenseMode durchgeführt.
Befehlszeile der Compilerabfrage: "c:\\brautomation\\as48\\as\\gnuinst\\v6.3.0\\bin\\i686-elf-gcc.exe" -fPIC -O0 -g -Wall -W 5880 9233 9881 -std=gnu11 -Wp,-v -E -dD -x c -m32  /dev/null
Fehler beim Abfragen des Compilers. Es wird ein Fallback auf keine Bitanzahl durchgeführt.
Befehlszeile der Compilerabfrage: "c:\\brautomation\\as48\\as\\gnuinst\\v6.3.0\\bin\\i686-elf-gcc.exe" -fPIC -O0 -g -Wall -W 5880 9233 9881 -std=gnu11 -Wp,-v -E -dD -x c   /dev/null
i686-elf-gcc.exe: error: 5880: No such file or directory
i686-elf-gcc.exe: error: 9233: No such file or directory
i686-elf-gcc.exe: error: 9881: No such file or directory
i686-elf-gcc.exe: error: /dev/null: No such file or directory
i686-elf-gcc.exe: warning: '-x c' after last input file has no effect
i686-elf-gcc.exe: fatal error: no input files
compilation terminated.

Es wurde der MSVC-IntelliSenseMode angegeben. Der Compiler (cl.exe) wird konfiguriert.
Der Compiler (cl.exe) kann nicht konfiguriert werden.
Es wurde kein geeigneter Compiler gefunden. Legen Sie "compilerPath" in "c_cpp_properties.json" fest.
cpptools/getCodeActions: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c (id: 8)
  Dateiermittlung: 14227 Datei(en) verarbeitet
  0 Datei(en) aus Datenbank entfernt
Die Ermittlung von Dateien ist abgeschlossen.
Offene Dateien werden analysiert...
Füllen Sie den Cache für die Includevervollständigung auf.
Die Analyse geöffneter Dateien ist abgeschlossen.
Verbleibende Dateien werden analysiert...
  Analyse: 0 Datei(en) verarbeitet
Die Analyse verbleibender Dateien ist abgeschlossen.
cpptools/resumeParsing
cpptools/getCodeActions: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c (id: 9)
Kompilierungsargumente für "C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\XXX\MESSAGING\UM_MESSAGE\UM_MESSAGE\UM_MESSAGE.C" werden gesendet.
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\TEMP\INCLUDES
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\TEMP\OBJECTS\STANDARD\PLC\.MAPPVIEW\BUILD\NODE_MODULES\NODE-SASS\SRC\SASS_TYPES
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\TEMP\OBJECTS\STANDARD\PLC\.MAPPVIEW\BUILD\NODE_MODULES\NAN
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\TEMP\OBJECTS\STANDARD\PLC\.MAPPVIEW\BUILD\NODE_MODULES\NODE-SASS\SRC\LIBSASS\INCLUDE
  Define-Anweisung: _DEBUG
  Define-Anweisung: UNICODE
  Define-Anweisung: _UNICODE
  stdver: ms_c17
  intelliSenseMode: windows-msvc-x64
IntelliSense-Server wird heruntergefahren: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\XXX\MESSAGING\UM_MESSAGE\UM_MESSAGE\UM_MESSAGE.C
Kompilierungsargumente für "C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\XXX\MESSAGING\UM_MESSAGE\UM_MESSAGE\UM_MESSAGE.C" werden gesendet.
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\TEMP\INCLUDES
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\BUR
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\XXX
  Define-Anweisung: _DEFAULT_INCLUDES
  Define-Anweisung: _SG4
  Define-Anweisung: _BUR_FORMAT_BRELF
  stdver: ms_c17
  intelliSenseMode: windows-msvc-x64
Nach Syntaxfehlern wird gesucht: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c
IntelliSense-Server wird heruntergefahren: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\XXX\MESSAGING\UM_MESSAGE\UM_MESSAGE\UM_MESSAGE.C
Kompilierungsargumente für "C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\XXX\MESSAGING\UM_MESSAGE\UM_MESSAGE\UM_MESSAGE.C" werden gesendet.
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\TEMP\INCLUDES
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\BUR
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\XXX
  Define-Anweisung: _DEFAULT_INCLUDES
  Define-Anweisung: _SG4
  Define-Anweisung: _BUR_FORMAT_BRELF
  stdver: ms_c17
  intelliSenseMode: windows-msvc-x64
IntelliSense-Server wird heruntergefahren: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\XXX\MESSAGING\UM_MESSAGE\UM_MESSAGE\UM_MESSAGE.C
Kompilierungsargumente für "C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\XXX\MESSAGING\UM_MESSAGE\UM_MESSAGE\UM_MESSAGE.C" werden gesendet.
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\TEMP\INCLUDES
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\BUR
  Includes: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\XXX
  Define-Anweisung: _DEFAULT_INCLUDES
  Define-Anweisung: _SG4
  Define-Anweisung: _BUR_FORMAT_BRELF
  stdver: ms_c17
  intelliSenseMode: windows-msvc-x64
IntelliSense-Update für Dateien in dieser Übersetzungseinheit wird in die Warteschlange eingereiht: C:\_PROJECTS\DOJOMDL\XXXTEMPLATETEST\LOGICAL\LIBRARIES\XXX\MESSAGING\UM_MESSAGE\UM_MESSAGE\UM_MESSAGE.C
cpptools/resumeParsing
cpptools/finishUpdateSquiggles
Anzahl von Fehlerwellenlinien: 138
Fehlerwellenlinien werden deaktiviert in: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c
IntelliSense-Zeit aktualisieren (Sek.): 2.923
cpptools/getFoldingRanges: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c (id: 10)
cpptools/getCodeActions: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c (id: 11)
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: file:///c%3A/_Projects/DojoMDL/XXXTemplateTest/Logical/Libraries/XXX/Messaging/UM_Message/UM_Message/UM_Message.c


> Yes to which one 😉? Always or only some times?

Yes to always. At least till now. Just minutes ago VSCode updated itself to 1.63 and now I can not see C/C++ errors.

**Comment by Radeonmann** [comment]
Thanks for the data, it was very helpful.

The problem is the `-W 5880 9233 9881` build option defined in Automation Studio.
![image](https://user-images.githubusercontent.com/13839232/145400755-3b149f74-8ed1-4ca3-8faa-e8676c9b9e32.png)
I pass the additional build options and ANSI C additional build options directly to the C/C++ extension. When the C/C++ extension queries gcc with these options, gcc returns an error.

It seems that some of the Additional build options are not passed to gcc by AS, but are only used for the Br.As.Build.exe, e.g. your -W options. So I have to figure out how to sanitize this field... I will plan it for the next release, but as it is more of a hobby project, I cannot tell you an exact date. Probably it will be before end of the year.

There is a workaround which you can use. By adding a define before the -W option, gcc thinks the -W content is part of the define. So you can just use a dummy define until I fixed the issue.
![image](https://user-images.githubusercontent.com/13839232/145403995-b8f06baa-bc3e-4531-a777-ec807e22c5bc.png)

**Comment by MaDill** [comment]
I defined the -W 5880 9233 9881 in the "Additional build options" to suppress some compiler warnings. The filed "ANSI C build options" and "IEC build options" are empty.

Thank you for the feedback.

**Comment by Radeonmann** [comment]
The real problem was, that the build options from the Cpu.pkg file was handed over to the C/C++ extension as one string. The C/C++ extension thought it was one single compiler argument and escaped the whole string when passing it to gcc.

For that reason not only the -W flags, but also multiple -D defines were not interpreted properly.

In the fixing commit the options string from the Cpu.pkg is split on each whitespace and handed over to the C/C++ extension as an array. It was tested with all documented AS build options (-W, -profile) and also with multiple defines.
