### ISSUE TITLE
Add date and time information to build script

### ISSUE THREAD

**Issue by priesf** [br-automation-com/vscode-brautomationtools#31]
When running the build* tasks with extension it would be nice to have some information about date and time. (Similar to the B&R environment) 
Maybe it is not necessary to add the date and time to each line entered in the terminal, but maybe at the start and the end. 
Could also be used to check for improvements of the build performance.

**Comment by Radeonmann** [comment]
I will look into it. What I can easily do is add the time at start and end and maybe also some time difference at end.

Something like:
```
2022.01.12 22:42:42.123 Starting Br.As.Build.exe
...
...
2022.01.12 22:44:42.123 Br.As.Build.exe finished with exit code 0, time since start 2min
```

I don't know how easy it will be to add a time for each line of output, as I just receive the command line output from the build process, which triggers an event on data. I never looked into it, but it may be not guaranteed to trigger an event on each line.
