### ISSUE TITLE
Parser of build output has time of log in filename

### ISSUE THREAD

**Issue by tatdakar** [br-automation-com/vscode-brautomationtools#41]
In case of a compile error or warning the "Problems" view lists the issues, but they can't be linked to the actual files. The reason is that the file url has the time of the log in it resulting in an invalid path.
I recognized that on my installation the file path are absolute and in the screenshot on they are relative.
I created a new project with default settings, so i hope the issue does not result from my AS settings.

**Comment by Radeonmann** [comment]
Thanks for the report.

I guess it might be related to the change I introduced in #31. It seems I need to update the detection pattern.

I will plan the issue for the next release after I confirmed the error in my test environment.

**Comment by tatdakar** [comment]
I downgraded to 0.0.5 and that fixed the issue. So that's probably it.

Btw, thanks for the great work!!

**Comment by Radeonmann** [comment]
Fixed it and it will be in the next release.

The pattern can now handle timestamps of different locales, but it can not handle 'special' locales with non latin characters, such as zh-TW or ar-EG, as it would make the regex much more complex.

If there is the need to add more locales by someone, please open a separate issue.
