### ISSUE TITLE
Technology guarding failing the build

### ISSUE THREAD

**Issue by basprins** [br-automation-com/vscode-brautomationtools#42]
Hi,
What a FANTASTIC initiative. I am a huge fan already, even though I can't compile our project (yet) ;-).

Is this something you recognize? 

16:08:28 System.IO.FileNotFoundException:  error :Could not load file or assembly 'BR.TechnologyGuarding.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
16:08:28 File name: 'BR.TechnologyGuarding.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by basprins** [comment]
reboot solved the problem (dohhh!)

**Comment by Radeonmann** [comment]
Good to hear, that the problem was solved.

The extension doesn't do the build itself, it just triggers the command line of the Automation Studio according to the description in the Help.

If you have such kind of build issues in the future, you can check if a build is possible from Automation Studio.

If it already fails there, it will be an issue with the project or AS installation. 

If it works there, it might be an issue with how I invoke the build.

Also nice to hear somebody is actually using the extension. I was a bit busy during the summer, but I hope I will find a bit time until the end of the year.

**Comment by basprins** [comment]
Yeah the strange thing was, that building from AS worked fine. But, it was all fresh installed. Ah, windows, right, a reboot now and then fixes stuff :).

I was wondering, is B&R aware of your vscode extension? Maybe they are interested in this initiatieve. It might not replace all features hosted in AS, but vscode is sooo light weight and yet so powerful when it comes to coding. Maybe they would like to become contributors of your extension? First impressions are really good! You did great work here!

**Comment by Radeonmann** [comment]
As the extension code is hosted in the B&R organization group, yes there are at least some B&R people aware of the extension. Actually I'm also with B&R.

The B&R Github organization is mostly from B&R application engineers around the world, who want to provide useful things for customers, such as samples, libraries...

I think the main development team is enoughly busy with their daily business, as they have to bring all the new features, maintain the existing functionality...

They did a very big contribution, which is in my point of view one of the key strengths of the B&R system. The system is open and sticks to the standards. So for the C/C++ there is no hidden black magic. All the required header files... are available and therefore I 'only' had to provide the proper header structure to the C/C++ extension. 
The build is also available with various options from the command line and with the Runtime Utility Center it is possible to make online transfers, offline installations... from the command line.

**Comment by basprins** [comment]
Hi @Radeonmann 
Ahh, so you have inside connections :). I was wondering how hard it must have been to reverse engineer quite some concepts in the B&R IDE / toolchains. 

I know and understand that the introduction page claims "this is not a B&R product" and "this addon is not intended to replace AS". But really, would you dare to do any forecast where this addon is going? Will it really stay at "just a sexy tool to write code", or will it receive new features over time like:
- gdb debug (step through code, watch variables, view memory plots) 
- install software
- allow to add new programs/libraries (which generates the cyclic/init/exit cpp files and makes the necessary adjustments to the  package.pkg and cpu.sw)

I REALLY like what you did so far. Automation studio put B&R on the map, sure. But the things is dated. It doesn't have a very good user experience. Stuff popping up and claiming focus constantly interfering with stuff I am doing is really annoying. 

It would make perfect sense to me to aim for "B&R PLC software development" in vscode, and draw the line where one needs to do the hardware part. The configuration might land in the middle (although it would make much more sense to get this in the vscode plugin as well).
