### ISSUE TITLE
Debugging 

### ISSUE THREAD

**Issue by nische** [br-automation-com/vscode-brautomationtools#43]
Hi, 
Maybe it is possible to attach the Debugger with gdb to debug libs directly in VSC 

BR, NiSche

**Comment by nische** [comment]
I searched a little bit in the AS files and found the GDB Debugger with a config batch. 
unfortunately i cant connect with my X20 CP 0484. 
If i try to connect to my remote target the following error returns:

`192.168.32.231:2323: Das System hat versucht, einem Verzeichnis, das sich auf einem mit JOIN zugeordneten Laufwerk befindet, ein Laufwerk mit SUBST zuzuordnen.`

Maybe the gdb server is not running on my device. 

therefore i trace my network traffic to check if some messages will send when AS start debugging but unfortunately there is no other trafic than the PVIMan and gdb. 
In my opinion the gdb server is started by a specific PVI Parameter. Did anyone have access to a PVI documentation to start the GDB server?

**Comment by Radeonmann** [comment]
I never checked the gdb files, but as far as I know there is no official documentation in th AS help how to invoke gdb.

I think some of the batch... files in the gnu tools directories are to create the specific compilers... for the B&R system and not to invoke the tools. But I also didn't check this in detail. 

gdb is a bit out of scope for my plan. But if you find how to work with the gdb, I may consider adding such a functionality.

**Comment by nische** [comment]
@jcbastosportela Thanks a lot for your feedback. I would be very grateful if you send me some infos to make gdb running. 
Can i contact you by the email on your profil?

**Comment by basprins** [comment]
Any chance you are willing to share this? Being able to debug B&R in VScode is gold. And really, the arguments of not showing a warning to debug live targets.... Isn't that the programmers responsibility, you don't have to warn that you shouldn't put a cat in the microwave either, right?
